# Generated by Django 6.0.5 on 2026-05-25 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Sujet de l'anomalie")),
                ('type_menace', models.CharField(choices=[('PHISHING', 'Phishing / Lien Suspect'), ('MALWARE', 'Fichier Suspect / Suspicion Malware'), ('NETWORK', 'Anomalie Réseau / Lenteur suspecte'), ('HARDWARE', 'Périphérique Suspect (USB)'), ('OTHER', 'Autre comportement anormal')], default='OTHER', max_length=20)),
                ('description', models.TextField(verbose_name='Détails du comportement suspect')),
                ('url_associee', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL suspecte analysée (CyberLink)')),
                ('ip_employe', models.GenericIPAddressField(verbose_name='Adresse IP de la machine cible')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_resolu', models.BooleanField(default=False)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_signales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
