# Generated by Django 6.0.5 on 2026-05-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='est_resolu',
        ),
        migrations.AddField(
            model_name='incident',
            name='statut',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours de traitement'), ('RESOLVED', 'Résolu / Traité')], default='PENDING', max_length=20, verbose_name="Statut de l'incident"),
        ),
    ]
