# Generated by Django 6.0.5 on 2026-05-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_remove_incident_est_resolu_incident_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='analyst_response',
            field=models.TextField(blank=True, null=True, verbose_name='SOC Analyst Response'),
        ),
        migrations.AddField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(verbose_name='Incident Description'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='ip_employe',
            field=models.GenericIPAddressField(verbose_name='Employee Endpoint IP'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='statut',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CRITICAL', 'Critical')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Incident Title'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type_menace',
            field=models.CharField(choices=[('PHISHING', 'Phishing / Suspicious Link'), ('MALWARE', 'Malware Suspicion'), ('NETWORK', 'Network Anomaly'), ('HARDWARE', 'Suspicious Device'), ('OTHER', 'Other Suspicious Activity')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='url_associee',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Associated URL'),
        ),
    ]
