# Generated by Django 6.0.5 on 2026-05-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_incident_analyst_response_incident_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='incidents/'),
        ),
    ]
