# Generated by Django 6.0.5 on 2026-05-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_incident_evidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='evidence',
        ),
    ]
